# Generated by Django 5.0.6 on 2026-05-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_ai_metadata'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='complaint',
            new_name='complaints__student_3cf27f_idx',
            old_name='complaints__student_3a6e8c_idx',
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='complaints__status__236904_idx',
            old_name='complaints__status__486882_idx',
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='complaints__priorit_e341c1_idx',
            old_name='complaints__priorit_2e4550_idx',
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='complaints__categor_2cd958_idx',
            old_name='complaints__categor_4067df_idx',
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='complaints__source__9727e4_idx',
            old_name='complaints__source__0ffb49_idx',
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='complaints__created_805464_idx',
            old_name='complaints__created_efda5f_idx',
        ),
    ]
