# Generated by Codex on 2026-05-30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_rename_complaints__student_3a6e8c_idx_complaints__student_3cf27f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_role', models.CharField(blank=True, max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='complaints.complaint')),
                ('transferred_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_transfers_made', to=settings.AUTH_USER_MODEL)),
                ('transferred_to_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='complaints.role')),
                ('transferred_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaint_transfers_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='complainttransfer',
            index=models.Index(fields=['complaint'], name='complaints__complai_1d0f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='complainttransfer',
            index=models.Index(fields=['transferred_to_user'], name='complaints__transfe_e8dbee_idx'),
        ),
        migrations.AddIndex(
            model_name='complainttransfer',
            index=models.Index(fields=['transferred_to_role'], name='complaints__transfe_795465_idx'),
        ),
        migrations.AddIndex(
            model_name='complainttransfer',
            index=models.Index(fields=['created_at'], name='complaints__created_c4eb44_idx'),
        ),
    ]
