# Generated by Codex on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complainttransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSecurityState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=50)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('username', 'role')},
            },
        ),
        migrations.AddIndex(
            model_name='loginsecuritystate',
            index=models.Index(fields=['username', 'role'], name='complaints__usernam_148612_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsecuritystate',
            index=models.Index(fields=['locked_until'], name='complaints__locked__177b9b_idx'),
        ),
    ]
