# Generated by Codex on 2026-05-30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_loginsecuritystate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=50)),
                ('event', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('locked', 'Locked')], max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='loginauditlog',
            index=models.Index(fields=['created_at'], name='complaints__created_6f68d9_idx'),
        ),
        migrations.AddIndex(
            model_name='loginauditlog',
            index=models.Index(fields=['username', 'role'], name='complaints__usernam_db44c8_idx'),
        ),
        migrations.AddIndex(
            model_name='loginauditlog',
            index=models.Index(fields=['event'], name='complaints__event_f1cf38_idx'),
        ),
    ]
