# Generated by Codex on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_loginauditlog'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE auth_user ALTER COLUMN username TYPE varchar(50);",
            reverse_sql="ALTER TABLE auth_user ALTER COLUMN username TYPE varchar(150);",
        ),
        migrations.AlterField(
            model_name='loginauditlog',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='loginsecuritystate',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
